Adjust locations of where templates should be inserted for each target
org-roam/org-roam pull request #1581
Opened 2021-07-10 19:52 UTC by Wetlize

###### Motivation for this change
This an alternative to #1579 solution to fix and close #1566. All it does is repositioning of the point, so the corresponding for each `org-capture-place-[type]` functions would do the right thing. From my internal semi-automatic testings this works with all currently available `type`x`target` combinations in `org-roam-capture` and better than #1579, which still has some flows. Please, read the linked issue with the alternative PR along with the commit message for this PR for more details.

2021-07-10 20:01 UTC, Wetlize commented
Oh wow, the produced highlight for the diff really blows here on the GH. Dammit, it's not as bad as it looks :)

2021-07-11 13:53 UTC, jethrokuan requested changes
:+1: The general direction of the fix looks good.

I think it would help to extract `move-point-based-on-capture-type-near` to an internal function within `org-roam-capture`, the `org-roam-capture--goto-location` function is already kinda unwieldy.

2021-07-11 17:54 UTC, Wetlize commented
@jethrokuan And done. I personally in favor of giant functions with some comments here and there, when it comes to things that heavily context dependent or only make sense to exist under a single common scope and never referenced in any other scope, but this can be a bit clumsy in Elisp. 

I've iterated a bit on this and only just now noticed that each capture target doesn't move point after setting it once, so the function doesn't need to be called under each target, but only once after the `pcase`. The mandatory argument was redundant too, so I removed that.

This solution was also written generalized, with assumption that some other capture types will require some level of adjustment, but it only looks like `plain` needs that. I think it's safe to keep it this way and if needed other types (e.g. some new ones) can easily extend this.

2021-07-12 04:37 UTC, jethrokuan approved these changes

2021-07-12 04:37 UTC, merged